In [1]:
%reset -f

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Create the targets

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

np.float64(3.0)

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [10]:
targets.sum() / targets.shape[0]

np.float64(0.45571428571428574)

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the week',
                                            'Daily Work Load Average', 'Distance to Work', 'Excessive Absenteeism'], axis=1)

In [12]:
print(data_with_targets.columns)

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'],
      dtype='object')


In [13]:
data_with_targets is data_preprocessed

False

## Select the inputs for the regression

In [14]:
data_with_targets.shape

(700, 11)

In [15]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,0:14]

## Standardize the data

In [17]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

   

    def __init__(self,columns):

        self.scaler = StandardScaler()

        self.columns = columns       

       

    def fit(self, X):       

        self.scaler.fit(X[self.columns])       

        return self

   

    def transform(self, X):       

        init_col_order = X.columns

        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns, index=X.index)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        X_all = pd.concat([X_not_scaled, X_scaled], axis=1)
        X_all = X_all[init_col_order]  # reorder columns to original order
        return X_all

In [19]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
# columns_to_scale = ['Month Value', 'Day of the week', 'Transportation Expense', 'Distance to Work',
       # 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       # 'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [21]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
absenteeism_scaler = CustomScaler(columns=columns_to_scale)

In [23]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [26]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 417         0         0         0         1    -0.673803   
 439         1         0         0         0    -0.388293   
 277         0         0         0         0     0.753746   
 527         0         0         0         1     1.039256   
 631         0         0         0         1    -0.959313   
 ..        ...       ...       ...       ...          ...   
 456         0         0         1         0    -0.102784   
 561         1         0         0         0     1.610276   
 532         0         0         1         0     1.324766   
 58          0         0         0         0     0.753746   
 36          0         0         0         1     0.468236   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 417                1.624567 -1.320435        -0.408580          1 -0.919030   
 439                0.190942  0.091435         0.532229          1 -0.019280   
 277                1.0360

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=40)

In [30]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [31]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train, y_train)

LogisticRegression()

In [35]:
reg.score(x_train, y_train)

0.7785714285714286

## manually check the accuracy

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,

In [37]:
model_outputs == y_train

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [38]:
np.sum((model_outputs == y_train))

np.int64(436)

In [39]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

np.float64(0.7785714285714286)

## Finding the intercept and coefficients

In [40]:
reg.intercept_

array([-1.72134439])

In [41]:
reg.coef_

array([[ 3.06555338,  0.35456481,  3.04802467,  0.84312968,  0.06983772,
         0.50098995, -0.28365285,  0.24754091, -0.02424049,  0.40409789,
        -0.29340586]])

In [42]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [43]:
feature_name = unscaled_inputs.columns.values

In [44]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     3.065553
1                 Reason_2     0.354565
2                 Reason_3     3.048025
3                 Reason_4     0.843130
4              Month Value     0.069838
5   Transportation Expense     0.500990
6                      Age    -0.283653
7          Body Mass Index     0.247541
8                Education    -0.024240
9                 Children     0.404098
10                    Pets    -0.293406

In [45]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.721344
1                 Reason_1     3.065553
2                 Reason_2     0.354565
3                 Reason_3     3.048025
4                 Reason_4     0.843130
5              Month Value     0.069838
6   Transportation Expense     0.500990
7                      Age    -0.283653
8          Body Mass Index     0.247541
9                Education    -0.024240
10                Children     0.404098
11                    Pets    -0.293406

## interpreting the coefficients

In [46]:
summary_table['Odds ratio'] = np.exp(summary_table['Coefficient'])
summary_table

Feature name  Coefficient  Odds ratio
0                Intercept    -1.721344    0.178826
1                 Reason_1     3.065553   21.446327
2                 Reason_2     0.354565    1.425560
3                 Reason_3     3.048025   21.073676
4                 Reason_4     0.843130    2.323628
5              Month Value     0.069838    1.072334
6   Transportation Expense     0.500990    1.650354
7                      Age    -0.283653    0.753028
8          Body Mass Index     0.247541    1.280872
9                Education    -0.024240    0.976051
10                Children     0.404098    1.497951
11                    Pets    -0.293406    0.745719

In [47]:
summary_table.sort_values('Odds ratio', ascending=False)

Feature name  Coefficient  Odds ratio
1                 Reason_1     3.065553   21.446327
3                 Reason_3     3.048025   21.073676
4                 Reason_4     0.843130    2.323628
6   Transportation Expense     0.500990    1.650354
10                Children     0.404098    1.497951
2                 Reason_2     0.354565    1.425560
8          Body Mass Index     0.247541    1.280872
5              Month Value     0.069838    1.072334
9                Education    -0.024240    0.976051
7                      Age    -0.283653    0.753028
11                    Pets    -0.293406    0.745719
0                Intercept    -1.721344    0.178826

## Testing the model

In [48]:
reg.score(x_test, y_test)

0.6785714285714286

In [49]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.57180769, 0.42819231],
       [0.28578953, 0.71421047],
       [0.27116671, 0.72883329],
       [0.76384822, 0.23615178],
       [0.07710515, 0.92289485],
       [0.37236341, 0.62763659],
       [0.17544272, 0.82455728],
       [0.2085635 , 0.7914365 ],
       [0.79025132, 0.20974868],
       [0.64994717, 0.35005283],
       [0.87043596, 0.12956404],
       [0.37823206, 0.62176794],
       [0.40217212, 0.59782788],
       [0.44756289, 0.55243711],
       [0.46062817, 0.53937183],
       [0.20529134, 0.79470866],
       [0.78135688, 0.21864312],
       [0.84624198, 0.15375802],
       [0.40683075, 0.59316925],
       [0.84977701, 0.15022299],
       [0.25755605, 0.74244395],
       [0.85633565, 0.14366435],
       [0.75288827, 0.24711173],
       [0.64880577, 0.35119423],
       [0.78474417, 0.21525583],
       [0.21028359, 0.78971641],
       [0.87047434, 0.12952566],
       [0.41648887, 0.58351113],
       [0.79712366, 0.20287634],
       [0.86353908, 0.13646092],
       [0.